version: "2.2"
#This is a 3-container app.  Each service defines a container
services:
  flask:
    container_name: web
    image: python:alpine3.6
  redis:
    container_name: redis
    image: redis:3.2.11
  mysql:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Welcome"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "naresh"
      MYSQL_PASSWORD: "Welcome"